### ISSUE TITLE
[contributhon][team-2] example with multiple camera/sensor inputs on Raspberry Pi

### ISSUE THREAD

**Issue by tony-jinwoo-ahn** [nnstreamer/nnstreamer-example#163]
# Team-2 is planning to:
### Make examples with multiple camera/sensor inputs on Raspberry Pi.

# Expected Result
* work on Raspberry Pi
  Raspberry Pi 에서 동작하는 Edge AI 데모 시나리오 예제들을 몇 개 구현한 뒤 제출하려고 합니다.
* process multiple camera input
  다중 카메라 입력을 받아서 동시에 처리하는 데모 시나리오 예제 구현
* process camera/sensor compound input
  카메라와 센서 입력을 동시에 받아서 상황을 파악하고 반응하는 데모 시나리오 예제 구현

# Team members
@cloudhs7
@JeonChangMin
@suehdn
@tony-jinwoo-ahn 

# question
* if you have purchased any usb camera/sensor, please recommend.
  구매에 앞서, 추천하실만한 카메라/센서 모듈이 있다면 공유 부탁드립니다. 
  이걸 써보니 가성비가 괜찮다든지, 이 카메라를 여러대 연결해봤는데 무사히 잘 동작했다든지... 
* if you have any experience with Raspberry Pi, please guide us for environment setup.
  최신 라즈비안 설치 후 우분투와 동일하게 환경세팅을 하면 되는 것인지, nnstreamer 기본 동작성을 이미 검증해보신 분이 있으신지 문의드립니다.

**Comment by gichan-jang** [comment]
> if you have any experience with Raspberry Pi, please guide us for environment setup.
In order to use nnstreamer in the arm arch, it is officially supported through the Tizen.
How about uploading the Tizen platform on the RPI?
There is an example tested in RPI4.
https://github.com/nnstreamer/nnstreamer-example/tree/master/Tizen.platform/Tizen_IoT_ImageClassification

3.0 Porting Guide/Setup RPI3 for Tizen Instruction : https://wiki.tizen.org/3.0_Porting_Guide/Setup_RPI3_for_Tizen_Instruction
If you have any problems or difficulties, feel free to ask questions.

**Comment by tony-jinwoo-ahn** [comment]
@gichan-jang   Thank you for guide. I've checked Tizen_IoT_ImageClassification document, and I have some questions.

1. Could you explain "client" usage example for more detail? There's only "server" usage example.
2. Should I run "server" on desktop PC, and run "client" on Raspberry Pi meanwhile? Shall I connect both through AP(e.g. ipTIME)  using ethernet cable?
3. if question 2 is false, shall I run both "server" and "client" on two Raspberry Pis? 

Thank you.

**Comment by gichan-jang** [comment]
@tony-jinwoo-ahn 
> 1. Could you explain "client" usage example for more detail? There's only "server" usage example. I hope to see what parameters/arguments you used for client.
A. You just specify the client. 
    $ nnstreamer_tizen_iot_image_classification server orange 192.168.1.1 5001
    $ nnstreamer_tizen_iot_image_classification client orange 192.168.1.1 5001

> 2.1. Should I run "server" on desktop PC, and run "client" on Raspberry Pi meanwhile? 
A. Yes. I also tested the server on ubuntu PC and the client on RPI. 

> 2.2 Shall I connect both through AP(e.g. ipTIME)  using ethernet cable?
A. I think it's possible.

**Comment by tony-jinwoo-ahn** [comment]
Thank you!
