### ISSUE TITLE
[tizen_iot_text_classification] libnnstreamer_protobuf.so: cannot open shared object file: No such file or directory.

### ISSUE THREAD

**Issue by tony-jinwoo-ahn** [nnstreamer/nnstreamer-example#173]
hello, I've built nnstreamer_tizen_iot_text_classification for ubuntu 18.04 on "RaspberryPi4B" and ubuntu 18.04 on  "laptop".
I've tested using Rpi4/PC for server/client and vice versa, and got error:
```
$ ./nnstreamer_tizen_iot_text_classification server tensorflow-lite $MYIP $MYPORT

** (nnstreamer_tizen_iot_text_classification:4824): CRITICAL **: 23:57:48.203: Cannot open protobuf(/usr/lib/nnstreamer/decoders/libnnstreamer_decoder_protobuf.so) with error libnnstreamer_protobuf.so: cannot open shared object file: No such file or directory.

(nnstreamer_tizen_iot_text_classification:4824): GStreamer-CRITICAL **: 23:57:48.208: gst_mini_object_unref: assertion 'mini_object != NULL' failed

... and error chain...

```

I have a question: *what package should I install exactly?*
I've installed:
``` 
sudo apt install libprotobuf-dev 
sudo apt install libprotobuf-c-dev
```
but seems not the answer.

Thank you.

**Comment by tony-jinwoo-ahn** [comment]
I've checked library installed already, and became root and tried again, but same error.

```
root@ubuntu:/usr/lib/nnstreamer/decoders# ls -alh
total 136K
drwxr-xr-x 2 root root 4.0K Sep  6 13:00 .
drwxr-xr-x 6 root root 4.0K Sep  3 12:55 ..
-rw-r--r-- 1 root root  32K Sep  4 12:31 libnnstreamer_decoder_bounding_boxes.so
-rw-r--r-- 1 root root  11K Sep  4 12:31 libnnstreamer_decoder_direct_video.so
-rw-r--r-- 1 root root  27K Sep  4 12:31 libnnstreamer_decoder_flatbuf.so
-rw-r--r-- 1 root root  15K Sep  4 12:31 libnnstreamer_decoder_image_labeling.so
-rw-r--r-- 1 root root  15K Sep  4 12:31 libnnstreamer_decoder_image_segment.so
-rw-r--r-- 1 root root  16K Sep  4 12:31 libnnstreamer_decoder_pose_estimation.so
-rw-r--r-- 1 root root 5.9K Sep  4 12:31 libnnstreamer_decoder_protobuf.so
```

libnnstreamer_decoder_protobuf.so already exists... I cannot figure out now.

**Comment by gichan-jang** [comment]
Hello, @tony-jinwoo-ahn 
1. `tizen_iot_text_classification` operates on tizenIoT platform. If you want to use this app, you have to install tizenIoT platform image on your RPI4.

2. try to install `protobuf-compiler17` and `libprotobuf17`

**Comment by tony-jinwoo-ahn** [comment]
Thank you, @gichan-jang 
I installed those you suggested on my Rpi and PC, but still same error.
anyway, thank you for your comment.

**Comment by gichan-jang** [comment]
@tony-jinwoo-ahn 
Please try again, `sudo apt install nnstreamer-protobuf`

**Comment by tony-jinwoo-ahn** [comment]
thank you. I would try ```sudo apt install nnstreamer-protobuf``` after the conflict is fixed.

**Comment by gichan-jang** [comment]
@tony-jinwoo-ahn 
nnstreamer-protobuf package conflict has been resolved.

**Comment by tony-jinwoo-ahn** [comment]
thank you!! 👍

**Comment by tony-jinwoo-ahn** [comment]
I tested and it's fixed OK.
I don't need to do "sudo apt install nnstreamer-protobuf".
I re-installed nnstreamer and it works OK.
