### ISSUE TITLE
tensor_filter_subplugin example is not registered correctly

### ISSUE THREAD

**Issue by giladnahor** [nnstreamer/nnstreamer-example#174]
When creating a filter sub plugin with nnstreamer-example and trying to run I get:
 nnstreamer_subplugin of temp(/usr/local/lib/nnstreamer/filters/libnnstreamer_filter_temp.so) is broken. It does not call register_subplugin with its init function.

While debugging I found that the nnstreamer_filter_probe (&NNS_support_temp); 
exits with an error.
Diving to nnstreamer_subplugin.c :: register_subplugin
I found that this line returns with error (1):
g_hash_table_insert (subplugins[type], g_strdup (name), spdata);

The name is propagated correctly to this function and the type is 0.
I would appreciate your help!
Thanks

**Comment by jaeyun-jung** [comment]
From #172
Default meson prefix is /usr/local. (https://mesonbuild.com/Builtin-options.html)

Now nnstreamer finds sub-plugins under '/usr/lib/nnstreamer/', the sub-plugin generated from template cannot be registered when building the project with default meson option.
We need to update the guide doc for this:


configuration with prefix option to build templated project.
```
$ meson --prefix=/usr build
```
