### ISSUE TITLE
New nnstreamer-examples are not included after build

### ISSUE THREAD

**Issue by YongjoonSeo** [nnstreamer/nnstreamer-example#209]
Following the build instruction described in [nnstreamer build examples](https://github.com/nnstreamer/nnstreamer/wiki/usage-examples-screenshots#build-examples-ubuntu-1604), newly created examples are not included in build products.

The followings are new nnstreamer examples.
- nnstreamer-example/native/example_object_detection_tensorflow_lite/nnstreamer_example_object_detection_tflite.py
- nnstreamer-example/native/example_face_detection_tflite/nnstreamer_example_face_detection_tflite.py

I think these new examples are not included because path for `git clone` command in the build instruction is from [nnsuite/nnstreamer-example](https://github.com/nnstreamer/nnstreamer/wiki/usage-examples-screenshots#build-examples-ubuntu-1604), not from [nnstreamer/nnstreamer-example](https://github.com/nnstreamer/nnstreamer-example).
Therefore, the problem will be solved if nnsuite/nnstreamer-example is updated or if the path in [build instruction](https://github.com/nnstreamer/nnstreamer/wiki/usage-examples-screenshots#build-examples-ubuntu-1604) is changed to `git clone https://github.com/nnstreamer/nnstreamer-example.git nnstreamer-example.git`.

**Comment by gichan-jang** [comment]
Thank you for reporting this issue!
I modified paths what you mentioned.
