### ISSUE TITLE
[tflite2] example of object detection with quantized SSD model.

### ISSUE THREAD

**Issue by kevinbingsong** [nnstreamer/nnstreamer-example#250]
Below is the float point model for object detection. Do you have example for quantized SSD model?

bash_script/example_object_detection_tensorflow_lite/gst-launch-object-detection-tflite.sh

**Comment by myungjoo** [comment]
Google "quantized SSD model". Then, you get:

https://github.com/tensorflow/models/issues/9371
and
https://github.com/tensorflow/tensorflow/issues/39037

You are trying to get tensorflow-lite or tensorflow models. You need to look at tensorflow community for tensorflow models. The tensorflow models in this repository are from there.

**Comment by kevinbingsong** [comment]
I have below quantized model and below labels file. But I don't know how to run nnstream command line with it. Seems the output BBox isn't compatiable with nnstream BBox process. Below model isn't have box_priors.txt. Do you have any example for the model?


ssd_mobilenet_v1_1.0_quant.tflite and labels_ssd_mobilenet_v1_1.0_quant.txt
--



--

**Comment by myungjoo** [comment]
Try google. What you are searching for is released by Google.

And it **DOES** have box_prior.txt
