### ISSUE TITLE
(gst-launch-1.0:31): GStreamer-CRITICAL **: 05:24:58.650: gst_mini_object_unref: assertion 'mini_object != NULL' failed

### ISSUE THREAD

**Issue by sherlockzym** [nnstreamer/nnstreamer-example#286]
I encountered an error executing the following command

root@ht-2288H-V5:/opt/nvidia/deepstream/deepstream-5.0# gst-launch-1.0 rtspsrc location=rtsp://admin:1234qwer@10.0.7.127:554/h264/ch1/main/av_stream latency=200 ! rtph264depay ! h264parse ! nvv4l2decoder ! nvvideoconvert ! video/x-raw, format=\(string\)BGRx ! videoconvert ! fakesink sync=false
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Progress: (open) Opening Stream
Progress: (connect) Connecting to rtsp://admin:1234qwer@10.0.7.127:554/h264/ch1/main/av_stream
Progress: (open) Retrieving server options
Progress: (open) Retrieving media info
Progress: (request) SETUP stream 0
Progress: (open) Opened Stream
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Progress: (request) Sending PLAY request
Progress: (request) Sending PLAY request
Progress: (request) Sent PLAY request

(gst-launch-1.0:31): GStreamer-CRITICAL **: 05:24:58.650: gst_mini_object_unref: assertion 'mini_object != NULL' failed
^Chandling interrupt.
Interrupt: Stopping pipeline ...
Execution ended after 0:00:03.065412691
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
^C

However, changing the decoder command does not report an error，I believe nvV4L2Decoder is the source of the problem

root@ht-2288H-V5:/opt/nvidia/deepstream/deepstream-5.0# gst-launch-1.0 rtspsrc location=rtsp://admin:1234qwer@10.0.7.127:554/h264/ch1/main/av_stream latency=200 ! rtph264depay ! h264parse ! avdec_h264 ! nvvideoconvert ! video/x-raw, format=\(string\)BGRx ! videoconvert ! fakesink sync=false
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Progress: (open) Opening Stream
Progress: (connect) Connecting to rtsp://admin:1234qwer@10.0.7.127:554/h264/ch1/main/av_stream
Progress: (open) Retrieving server options
Progress: (open) Retrieving media info
Progress: (request) SETUP stream 0
Progress: (open) Opened Stream
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Progress: (request) Sending PLAY request
Progress: (request) Sending PLAY request
Progress: (request) Sent PLAY request
Redistribute latency...
Redistribute latency...
^Chandling interrupt.
Interrupt: Stopping pipeline ...
Execution ended after 0:00:34.124400984
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...
 
I use a docker
https://docs.nvidia.com/metropolis/deepstream/5.0.1/dev-guide/text/DS_docker_containers.html
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/deepstream
docker run --gpus all -it --rm --net=host --privileged -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -w /opt/nvidia/deepstream/deepstream-5.0 nvcr.io/nvidia/deepstream:5.0.1-20.09-devel

root@ht-2288H-V5:/opt/nvidia/deepstream/deepstream-5.0# gst-launch-1.0 --version
gst-launch-1.0 version 1.14.5
GStreamer 1.14.5
https://launchpad.net/distros/ubuntu/+source/gstreamer1.0

**Comment by sherlockzym** [comment]
But there is no problem with the following docker
docker run --gpus all -it --rm --net=host --privileged -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -w /opt/nvidia/deepstream/deepstream-6.1 nvcr.io/nvidia/deepstream:6.1-devel

root@ht-2288H-V5:/opt/nvidia/deepstream/deepstream-6.1# gst-launch-1.0 rtspsrc location=rtsp://admin:1234qwer@10.0.7.127:554/h264/ch1/main/av_stream latency=200 ! rtph264depay ! h264parse ! nvv4l2decoder ! nvvideoconvert ! video/x-raw, format=\(string\)BGRx ! videoconvert ! fakesink sync=false
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Progress: (open) Opening Stream
Progress: (connect) Connecting to rtsp://admin:1234qwer@10.0.7.127:554/h264/ch1/main/av_stream
Progress: (open) Retrieving server options
Progress: (open) Retrieving media info
Progress: (request) SETUP stream 0
Progress: (open) Opened Stream
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Progress: (request) Sending PLAY request
Progress: (request) Sending PLAY request
Progress: (request) Sent PLAY request


root@ht-2288H-V5:/opt/nvidia/deepstream/deepstream-6.1# gst-launch-1.0 --version
gst-launch-1.0 version 1.16.2
GStreamer 1.16.2
https://launchpad.net/distros/ubuntu/+source/gstreamer1.0

**Comment by anyj0527** [comment]
I think you may ask to deepstream, not us (nnstreamer).
