### ISSUE TITLE
nnstreamer_example_cam gst_mini_object_unref: assertion 'mini_object != NULL' failed

### ISSUE THREAD

**Issue by zerocurve** [nnstreamer/nnstreamer-example#99]
When run the example on Mac 10.15

Any idea how to fix it?

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.544: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.544: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.544: gst_caps_can_intersect: assertion 'GST_IS_CAPS (caps1)' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.544: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.544: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.545: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.545: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.545: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.545: gst_caps_can_intersect: assertion 'GST_IS_CAPS (caps2)' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.545: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.545: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.545: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.545: gst_pad_template_new: assertion 'caps != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.545: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.545: gst_element_request_compatible_pad: assertion 'GST_IS_PAD_TEMPLATE (templ)' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.545: gst_object_unref: assertion 'object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.545: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.545: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.546: gst_caps_can_intersect: assertion 'GST_IS_CAPS (caps2)' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.546: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.546: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.546: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.546: gst_pad_template_new: assertion 'caps != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.546: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.546: gst_element_request_compatible_pad: assertion 'GST_IS_PAD_TEMPLATE (templ)' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.546: gst_object_unref: assertion 'object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.548: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.548: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.548: gst_caps_can_intersect: assertion 'GST_IS_CAPS (caps1)' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.548: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.549: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(nnstreamer_example_cam:4410): GStreamer-CRITICAL **: 15:02:39.549: gst_mini_object_ref: assertion 'mini_object != NULL' failed

** (nnstreamer_example_cam:4410): CRITICAL **: 15:02:39.571: _set_window_title: assertion 'element != NULL' failed

** (nnstreamer_example_cam:4410): CRITICAL **: 15:02:39.571: _set_window_title: assertion 'element != NULL' failed
^C

**Comment by myungjoo** [comment]
Please show more info of your error. You may put logs printed with GST_DEBUG enabled. Besides, you should show us your environment, how you built, and how you run.

ps. I'm not sure who's got Mac environment right now.

**Comment by bartkim0426** [comment]
Try to change video src and sink in mac OS X (ex. v4l2src -> autovideosrc, ximagesink -> autovideosink) @zerocurve

**Comment by myungjoo** [comment]
No follow-ups from the issue raiser. Closing this.
